version: '3.8'
services:
  postgres_db:
    image: postgres:15-alpine
    container_name: nest_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apnar_password
      POSTGRES_DB: apnar_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data

  nest_app:
    build: .
    container_name: nest_prisma_app_container
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: "postgresql://postgres:1234@postgres_db:5432/nest-prisma-app?schema=public"

volumes:
  pgdata:
